# Generated by Django 5.0.4 on 2024-04-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('max_slots', models.IntegerField()),
                ('rest_slots', models.IntegerField()),
                ('day', models.CharField(max_length=255)),
                ('first_period', models.IntegerField()),
                ('number_period', models.IntegerField()),
                ('room', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('week', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.subject')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['group'],
            },
        ),
    ]
