# Generated by Django 5.0.4 on 2024-04-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=255, unique=True)),
                ('name', models.TextField()),
                ('credit', models.IntegerField()),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
    ]
