# Generated by Django 5.0.4 on 2024-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCourse',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'register_course',
            },
        ),
    ]
